-- AlterTable
ALTER TABLE "Unit" ADD COLUMN     "bathrooms" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bedrooms" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rentAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
